version: '2.1'

services:
  pulumi:
    image: pulumi
    build: .
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    env_file:
      # where your pulumi token should be
      - pulumi.env
    environment:
      # needs this for deploying using windows
    - VIRTUALENV_ALWAYS_COPY=1

